### ISSUE TITLE
404 when we don't have stats for an address #38

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-indexer#39]
https://indexer.testnet.taraxa.io/address/0xebec795c9c8bbd61ffc14a6662944748f299cacf/stats

Return 404 error when we don't have data for an address + empty object.

This endpoint should return a 200 OK response with an empty stats object:
```
{
  "dagsCount": 0,
  "lastDagTimestamp": null,
  "pbftCount": 0,
  "lastPbftTimestamp": null,
  "transactionsCount": 0,
  "lastTransactionTimestamp": null
}
```

It doesn't mean that the address doesn't exists, it just means that we don't have any data for it.

**Comment by kstdl** [comment]
We have two options here:
1. As it is right now. Don't return this timestamps if it wasn't set 
2. return 0 for "empty timestamp"
