### ISSUE TITLE
Discrepancies between GraphQL and indexer

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-indexer#41]
LE: Could it be because we the faucet send transactions to itself? But the GraphQL has more than 50% more transactions.

The transaction count for the faucet address seems to be very different between GraphQL and the indexer on the testnet.

```
curl 'https://graphql.testnet.taraxa.io/' \
  -H 'accept: application/graphql+json, application/json' \
  -H 'content-type: application/json' \
  -H 'pragma: no-cache' \
  --data-raw $'{"query":"query get_address_data($account: Address\u0021) {\\n  block {\\n    hash\\n    number\\n    account(address: $account) {\\n      address\\n      balance\\n      transactionCount\\n      code\\n      __typename\\n    }\\n    __typename\\n  }\\n}","operationName":"get_address_data","variables":{"account":"0xf4a52b8f6dc8ab046fec6ad02e77023c044342e4"}}' \
  --compressed
```
vs

https://indexer.testnet.taraxa.io/address/0xf4a52b8f6dc8ab046fec6ad02e77023c044342e4/stats

**Comment by kstdl** [comment]
GraphQL have less transactions, not more. And this is because it returns nonce that is not precisely transaction count and it only counts sent transactions.
